spring.application.name=food-service

#Base URL
server.servlet.context-path=/api

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/food_service
spring.datasource.username=postgres
spring.datasource.password=123

#Hibernate
spring.jpa.hibernate.ddl-auto=create-drop

#Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.security=DEBUG

#JWT
jwts.secret=v9Y$B&E(H+MbQeThWmZq4t7w!z%C*F-J
jwts.expiration-ms=900000