spring.application.name=food-service

#Base URL
server.servlet.context-path=/api

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/food_service
spring.datasource.username=postgres
spring.datasource.password=123

#Hibernate
spring.jpa.hibernate.ddl-auto=create-drop